name: Build and deploy portfolio

# deploy on push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies 
        run: |
          npm install
      - name: Build angular app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          npm install angular-cli-ghpages@2.0.3
        with:
          branch: gh-pages
          folder: dist
