name: Build and deploy portfolio

# Trigger deployment on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Angular app
      - name: Build Angular app
        run: npm run build --prod

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/portfolio
