name: Build and deploy portfolio

# Trigger deployment on push to the main branch or via manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      # Step 2: Set up Node.js
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Angular app
      - name: Build Angular app
        run: npm run build --prod

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "palejorniel@gmail.com"
          git config --global user.name "print-Eruki"
          npx angular-cli-ghpages --dir=dist/portfolio --no-silent
